<?php


return [
    "GOOGLE_DRIVE_CLIENT_ID" => env('GOOGLE_DRIVE_CLIENT_ID', "695947900217-3506tso7rc1bkr6j4a72kcdjqli62gs8.apps.googleusercontent.com"),
    "GOOGLE_DRIVE_CLIENT_SECRET" => env('GOOGLE_DRIVE_CLIENT_SECRET', "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"),
    "GOOGLE_DRIVE_REFRESH_TOKEN" => env('GOOGLE_DRIVE_REFRESH_TOKEN', "1//046wCgKbdekpACgYIARAAGAQSNwF-L9IrKaaD-6FxVFPNZbnVlNG3kxBfeYmd67TaF6qeMgCNL76Cw9al-OwfQhlGrQDvuBh6Rg0"),
    "GOOGLE_DRIVE_BACKUP_FOLDER_ID" => env('GOOGLE_DRIVE_BACKUP_FOLDER_ID', "1oV4yAT0sxh98rWMBcizHW4v3JFdWHUBJ"),
    "App_Name" => 'My App'
];
